Feature branch1
willy836/Hello-world pull request #1
Opened 2022-08-16 12:38 UTC by willy836

Create a branch called feature-branch1

2022-08-16 13:11 UTC, omarsalem7 requested changes
Hi @willy836 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
- Descriptive commit messages ✔️

## Required Changes ♻️

- [ ]  Kindly update your readme by using [Microverse template](https://github.com/microverseinc/readme-template/blob/master/README.md)
- [ ] Kindly set up linters correctly by following [this link](https://github.com/microverseinc/linters-config/tree/master/html-css)
- [ ] Also consider adding code for index HTML with `h1` contain hello world
- [ ] Consider adding a descriptive pull request by clicking in edit button and adding a description with what you did in this project like: `I created my hello world project`, `I set up linters`, `I styled `h1``

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 15:41 UTC, willy836 commented
I updated my hello word project, i set up linters, added a descriptive readme, and added a header in the index.html file

2022-08-16 17:29 UTC, vickymarz requested changes
Hi @willy836 , 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 

 ## Required Changes ♻️

- [ ] As the previous reviewer has suggested, Kindly follow this [link](https://github.com/microverseinc/linters-config/tree/master/html-css) to set up linters correctly. Currently, your linters are lacking the stylelint and the web hint config files 👍🏼 . 

- [ ] Kindly reminder to add node_modules to gitignore which will be generated while setting up linters in your project 😄.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 17:29 UTC, vickymarz commented on README.md
> +Contributions, issues, and feature requests are welcome!
- [ ] You have done well updating your readme 😄 as the previous reviewer suggested, but I think you should improve on your readme by following the template provided by Microverse. Please ensure your readme looks like the[ template](https://github.com/microverseinc/readme-template/blob/master/README.md) provided 👍🏼 .

2022-08-17 08:36 UTC, willy836 commented
hello
after setting up my linters, node_modules were not generated. help

On Tue, Aug 16, 2022 at 8:29 PM Okoroji Victor Ebube <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @willy836 <https://github.com/willy836> ,
>
> Great work on making the changes requested by a previous reviewer 👏 🔥
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
>
>
> <https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966>
> Top highlight 🎯
>
>    - The PR title and description are professional and descriptive ✅
>
> Required Changes ♻️
>
>    -
>
>    As the previous reviewer has suggested, Kindly follow this link
>    <https://github.com/microverseinc/linters-config/tree/master/html-css>
>    to set up linters correctly. Currently, your linters are lacking the
>    stylelint and the web hint config files 👍🏼 .
>    -
>
>    Kindly reminder to add node_modules to gitignore which will be
>    generated while setting up linters in your project 😄.
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In README.md
> <https://github.com/willy836/Hello-world/pull/1#discussion_r947059245>:
>
> > -# Hello-world
>
> \ No newline at end of file
>
> +Hello-Microverse
>
> +This project contains a few lines of basic html and css, a readme file and .gitignore file
>
> +
>
> +Built With
>
> +HTML
>
> +CSS
>
> +
>
> +Authors
>
> +GitHub: @willy836
>
> +Twitter: @wkimiri
>
> +LinkedIn: Wilson Kimiri
>
> +
>
> +Contributing
>
> +Contributions, issues, and feature requests are welcome!
>
>
>
>    - You have done well updating your readme 😄 as the previous reviewer
>    suggested, but I think you should improve on your readme by following the
>    template provided by Microverse. Please ensure your readme looks like the
>    template
>    <https://github.com/microverseinc/readme-template/blob/master/README.md>
>    provided 👍🏼 .
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/willy836/Hello-world/pull/1#pullrequestreview-1074508951>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZQDCSGYYLZROSYEYNJWTMTVZPFZLANCNFSM56VVKTMA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-17 09:41 UTC, willy836 commented
When setting up my linters, I noticed the npm commands were not working, so I just copied and pasted the files. Also, no node_modules were generated. I updated the readme following the template provided.

2022-08-17 09:48 UTC, vickymarz commented
@willy836 did you do npm init -y ?

2022-08-17 09:52 UTC, zhadier approved these changes
## Hi @willy836  👋  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

<img src="https://media2.giphy.com/media/ByeYxURXxPyptxD2ta/giphy-downsized-medium.gif"/>

# Congratulations! 🎉 

✔️ No linter errors
✔️ Professional pull request title and description

### Keep Rocking!👏👏👏
## Optional
- [ ] [ _Optional_ ] Kindly always add `node_modules` in your `.gitignore` file as a best practice, irrespective of whether they exist in the project or not. There's no harm in adding it to .gitignore even if the node_modules do not exist. It can be considered a safeguard if you decide to add dependencies and generate modules in the future.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 10:36 UTC, merged

2022-08-17 11:44 UTC, willy836 commented
@

Okoroji Victor Ebubeyes. i did npm init -y but it still didnt work

On Wed, Aug 17, 2022 at 12:53 PM Zeeshan Haider ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> Hi @willy836 <https://github.com/willy836> 👋
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
>
>
> <https://camo.githubusercontent.com/4ef899d2146e4509b8eebd93b91fd34d7fa27ba290a66f3d94e9e551ec2714d5/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4279655978555258785079707478443274612f67697068792d646f776e73697a65642d6d656469756d2e676966>
> Congratulations! 🎉
>
> ✔️ No linter errors
> ✔️ Professional pull request title and description
> Keep Rocking!👏👏👏 Optional
>
>    - [ *Optional* ] Kindly always add node_modules in your .gitignore
>    file as a best practice, irrespective of whether they exist in the project
>    or not. There's no harm in adding it to .gitignore even if the node_modules
>    do not exist and in the future, it can be considered a safeguard if you
>    decide to add dependencies and generate modules.
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/willy836/Hello-world/pull/1#pullrequestreview-1075405684>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZQDCSD2UBNR4UAHYLIANT3VZSY7ZANCNFSM56VVKTMA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-17 11:49 UTC, vickymarz commented
@willy836 if you run the commands in the linters.yml for the webhint and stylint installation, you will see the node modules generated. It seems you didn't run those commands in your terminal.

2022-08-17 15:38 UTC, willy836 commented
@Victor, yes. They are running on terminal. I was previously running the
commands on gitbash. Thanks!!

On Wed, Aug 17, 2022 at 2:49 PM Okoroji Victor Ebube <
***@***.***> wrote:

> @willy836 <https://github.com/willy836> if you run the commands in the
> linters.yml for the webhint and stylint installation, you will see the node
> modules generated. It seems you didn't run those commands in your terminal.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/willy836/Hello-world/pull/1#issuecomment-1217905695>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZQDCSA3XXG4EX6M7U5MIDDVZTGVNANCNFSM56VVKTMA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>